EasyRent/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')), # Подключаем маршруты из приложения core
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'core'

urlpatterns = [
    # Основные страницы
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='core:home'), name='logout'),
    path('properties/', views.property_list, name='property_list'),
    path('profile/', views.profile, name='profile'),

    # Страницы взаимодествия с недвижимостью
    path('properties/create/', views.property_create, name='property_create'),
    path('property/<int:property_id>/request/', views.viewing_request, name='viewing_request'),
    path('realtor_properties/', views.realtor_properties, name='realtor_properties'),

    # Страницы для профиля пользователя
    path('my_requests/', views.my_viewing_requests, name='my_viewing_requests'),
    path('my_rental_agreements/', views.my_rental_agreements, name='my_rental_agreements'),

    # Работа с договорами со стороны пользователя
    path('rental_agreement/<int:request_id>/', views.create_rental_agreement, name='create_rental_agreement'),
    path('rental_agreement/confirm/<int:agreement_id>/', views.confirm_rental_agreements, name='confirm_rental_agreements'),

    # Работа с запросами на просмотр со стороны риелтора 
    path('realtor_viewing_requests/', views.realtor_viewing_requests, name='realtor_viewing_requests'),
    path('viewing_requests/confirm/<int:viewing_request_id>/', views.confirm_viewing_requests, name='confirm_viewing_requests'),
    path('viewing_requests/cancel/<int:viewing_request_id>/', views.cancel_viewing_requests, name='cancel_viewing_requests'),

    # Работа с договорами со стороны риелтора
    path('realtor_rental_agreements/', views.realtor_rental_agreements, name='realtor_rental_agreements'),
    path('realtor_sent_agreements/<int:agreement_id>/', views.realtor_sent_agreements, name='realtor_sent_agreements'),
    path('realtor_cancel_sent_agreements/<int:agreement_id>/', views.realtor_cancel_sent_agreements, name='realtor_cancel_sent_agreements'),
    path('realtor_confirm_rental_agreements/<int:agreement_id>/', views.realtor_confirm_rental_agreements, name='realtor_confirm_rental_agreements'),
    ]

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.core.mail import send_mail

# Модель пользователя с ролями
class User(AbstractUser):

    ROLE_CHOICES = [
        ('admin', 'Администратор'),
        ('realtor', 'Риелтор'),
        ('client', 'Клиент'),   
    ]

    role = models.CharField(
        max_length=10,
        choices=ROLE_CHOICES,
        default='client',
    )

    def get_icon(self):
        # Если роль пользователя 'admin', то возвращаем иконку admin.png
        if self.role == 'admin':
            return f"Icons/15.png"
        else:
            # Для всех остальных пользователей выбираем иконку по остаточному значению от деления на 20
            icon_number = self.id % 16  # Получаем остаток от деления id на 20
            return f"Icons/{icon_number + 1}.png"  # Иконка будет иметь номер от 1 до 20

    def save(self, *args, **kwargs):
        if self.is_superuser:
            self.role = 'admin'
        super().save(*args, **kwargs)

    #Метод для отправки сообщения о подтверждении на просмотр
    def send_confirmation_email(self, viewing_request):
        subject = 'Подтверждение на просмотр'
        message = (
            f'Здравствствуйте, {self.username}!\n\n'
            f"Ваш запрос на просмотр объекта недвижимости {viewing_request.property.title} был"
            f"Дата просмотра: {viewing_request.viewing_time.strftime('%d-%m-%Y')}\n"
            f"Местоположение: {viewing_request.property.location}\n\n"
            f"Цена: {viewing_request.property.price} руб.\n\n"
            f"С уважением,\nEasy Rent."
        )
        recipient = self.email
        send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [recipient])

        
    def __str__(self):
        return f"{self.username} ({self.get_role_display()})"

# Модель объявления о недвижимости
class Property(models.Model):
    PROPERTY_STATUS = [
        ('available', 'Свободно'),
        ('rented', 'Сдано'),
    ]

    title = models.CharField(max_length=100)
    description = models.TextField()
    area = models.DecimalField(max_digits=8, decimal_places=2)
    location = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=10, choices=PROPERTY_STATUS, default='available')
    realtor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='properties',
        limit_choices_to={'role': 'realtor'},
        null=True,  # На случай, если нужно оставить недвижимость без риелтора
        blank=True
    )
    
    def __str__(self):
        return self.title
    
# Модель запроса на просмотр
class ViewingRequest(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Ожидает подтверждения'),
        ('confirmed', 'Подтверждено'),
    ]

    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    realtor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='viewing_requests_as_realtor', verbose_name="Риелтор", null=True)
    request_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    viewing_time = models.DateField() # Время, когда клиент хочет посмотреть объект 

    def __str__(self):
        return f'Запрос на просмотр {self.property.title} от {self.user.username}'
    
# Модель договора
class RentalAgreement(models.Model):
    STATUS_CHOICES = [
        ('pending_sent', 'Ожидает отправления'),
        ('sent', 'Отправлено'),
        ('pending_confirmed', 'Ожидает подтверждения'),
        ('confirmed', 'Подтверждено'),
    ]

    viewing_request = models.OneToOneField(ViewingRequest, on_delete=models.CASCADE)
    tenant = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tenant_agreements')
    realtor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='realtor_agreements', verbose_name="Риелтор", null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    rent_price = models.DecimalField(max_digits=10, decimal_places=2)
    signed_date = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='pending_sent')

    def __str__(self):
        return f"Договор аренды: {self.viewing_request.property.title} - {self.tenant.username}"
    

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail
from django.contrib.auth import login, authenticate, logout
from django.conf import settings
from .forms import UserRegisterForm, PropertyCreateForm, ViewingRequestForm, RentalAgreementForm
from .models import Property, ViewingRequest, RentalAgreement
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
import threading
from concurrent.futures import ThreadPoolExecutor

import logging

logger = logging.getLogger(__name__)
executor = ThreadPoolExecutor(max_workers=5)

def home(request):
    return render(request, 'core/home.html')

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user) # Автоматический вход
            return redirect('core:home')
    else:
        form = UserRegisterForm()
    return render(request, 'core/register.html', {'form': form})


def property_list(request):
    sort_by = request.GET.get('sort', 'price')  # Получаем параметр сортировки, по умолчанию 'price'

    if sort_by == 'price':
        properties = Property.objects.order_by('price')  # Сортировка по цене (по возрастанию)
    elif sort_by == '-price':
        properties = Property.objects.order_by('-price')  # Сортировка по цене (по убыванию)
    elif sort_by == 'area':
        properties = Property.objects.order_by('area')  # Сортировка по метражу (по возрастанию)
    elif sort_by == '-area':
        properties = Property.objects.order_by('-area')  # Сортировка по метражу (по убыванию)
    else:
        properties = Property.objects.all()  # Без сортировки
    return render(request, 'core/property_list.html', {'properties': properties})

@login_required
def property_create(request):
    if request.method == 'POST':
        form = PropertyCreateForm(request.POST)
        if form.is_valid():
            property = form.save(commit=False)
            property.realtor = request.user
            property.save()
            return redirect('core:realtor_properties')  # Перенаправляем на список недвижимости
    else:
        form = PropertyCreateForm()
    return render(request, 'core/property_create.html', {'form': form})

@login_required
def viewing_request(request, property_id):
    property_instance = Property.objects.get(id=property_id) 
    
    if request.method == 'POST':
        form = ViewingRequestForm(request.POST)
        if form.is_valid():
            # Создаем новый запрос на просмотр
            viewing_request = form.save(commit=False)
            viewing_request.user = request.user
            viewing_request.property = property_instance
        
            viewing_request.status = 'pending'
            viewing_request.save()
            return redirect('core:property_list')  # Перенаправляем на список недвиж
    else:
        form = ViewingRequestForm()

    return render(request, 'core/viewing_request.html', {'form': form, 'property': property_instance})

@login_required
def my_viewing_requests(request):
    # Получаем все запросы текущего пользователя
    viewing_requests = ViewingRequest.objects.filter(user=request.user)
    return render(request, 'core/my_viewing_requests.html', {'viewing_requests': viewing_requests})

@login_required
def create_rental_agreement(request, request_id):
    viewing_request = get_object_or_404(ViewingRequest, id=request_id, realtor=request.user)
    
    # Проверяем, что запрос подтверждён
    if viewing_request.status != 'confirmed':
        return HttpResponseForbidden("Вы можете создать договор только для подтверждённых запросов.")

    if request.method == 'POST':
        form = RentalAgreementForm(request.POST)
        if form.is_valid():
            rental_agreement = form.save(commit=False)
            rental_agreement.viewing_request = viewing_request
            rental_agreement.realtor = request.user
            rental_agreement.tenant = viewing_request.user
            rental_agreement.save()
            return redirect('core:realtor_rental_agreements') 
    else:
        form = RentalAgreementForm()

    return render(request, 'core/create_rental_agreement.html', {
        'form': form, 
        'viewing_request': viewing_request
    })

@login_required
def profile(request):
    return render(request, 'core/profile.html')

@login_required
def my_rental_agreements(request):
    agreements = RentalAgreement.objects.filter(viewing_request__user=request.user).exclude(status='pending_sent')
    return render(request, 'core/my_rental_agreements.html', {'agreements': agreements})

@login_required
def confirm_rental_agreements(request, agreement_id):
    
    agreement = get_object_or_404(RentalAgreement, id=agreement_id)

    if agreement.status == 'sent':
        agreement.status = 'pending_confirmed'
        agreement.save()
    return redirect('core:my_rental_agreements')


@login_required
def realtor_properties(request):
    properties = Property.objects.filter(realtor=request.user)
    return render(request, 'core/realtor_properties.html', {'properties': properties})

@login_required
def realtor_viewing_requests(request):
    viewing_requests = ViewingRequest.objects.filter(realtor=request.user)
    return render(request, 'core/realtor_viewing_requests.html', {'viewing_requests': viewing_requests})

@login_required
def confirm_viewing_requests(request, viewing_request_id):

    viewing_request = get_object_or_404(ViewingRequest, id=viewing_request_id)

    # Меняем статус записи на "подтверждена"
    if viewing_request.status == 'pending':
        viewing_request.status = 'confirmed'
        viewing_request.save()

    subject='Подтверждение запроса на просмотр'  # Тема письма
    message=f'Здравствуйте, {viewing_request.user.username} # ваш запрос на просмотр недвижимости был подтвержден.',  # Тело письма
    #recipient=[viewing_request.user.email]  # Получатель
    recipient=['komlev.artem.02@mail.ru']  # Получатель
    #send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [recipient])
    #send_mail('Django mail', 'This e-mail was sent with Django.', settings.DEFAULT_FROM_EMAIL, ['komlev.artem.02@mail.ru'], fail_silently=False)
    #send_async_email(subject, message, recipient) # Ассинхронная функция для отправки email
     # Запускаем отправку письма в отдельном потоке
    threading.Thread(target=send_async_email, args=(subject, message, recipient)).start()

    return redirect('core:realtor_viewing_requests')

@login_required
def cancel_viewing_requests(request, viewing_request_id):

    viewing_request = get_object_or_404(ViewingRequest, id=viewing_request_id)

    # Меняем статус записи на "подтверждена"
    if viewing_request.status == 'confirmed':
        viewing_request.status = 'pending'
        viewing_request.save()
    
    return redirect('core:realtor_viewing_requests')

@login_required
def realtor_rental_agreements(request):
    agreements = RentalAgreement.objects.filter(realtor=request.user)
    return render(request, 'core/realtor_rental_agreements.html', {'agreements': agreements})

@login_required
def realtor_sent_agreements(request, agreement_id):
    agreement = get_object_or_404(RentalAgreement, id=agreement_id)

    if agreement.status == 'pending_sent':
        agreement.status = 'sent'
        agreement.save()
    
    return redirect('core:realtor_rental_agreements')

@login_required
def realtor_cancel_sent_agreements(request, agreement_id):
    agreement = get_object_or_404(RentalAgreement, id=agreement_id)

    if agreement.status == 'sent' or agreement.status == 'confirmed':
        agreement.status = 'pending_sent'
        agreement.save()
    
    return redirect('core:realtor_rental_agreements')

@login_required
def realtor_confirm_rental_agreements(request, agreement_id):
    agreement = get_object_or_404(RentalAgreement, id=agreement_id)

    if agreement.status == 'pending_confirmed':
        agreement.status = 'confirmed'
        agreement.save()

    return redirect('core:realtor_rental_agreements')


def send_async_email(subject, message, recipient_email):
    try:
        send_mail(
            subject,
            message,
            settings.DEFAULT_FROM_EMAIL,  # Email отправителя (берётся из настроек)
            [recipient_email],           # Список получателей
            fail_silently=False          # Если ошибка, то выбрасывать исключение
        )
        print(f"Email отправлен: {recipient_email}")
    except Exception as e:
        print(f"Ошибка при отправке email: {e}")

core/templates/core/create_rental_agreement.html
{% extends 'base.html' %}

{% block content %}
<div class="center-container">
    <h2 class="custom-h2">Создание договора аренды для {{ viewing_request.property.title }}</h2>

    <form method="post" class = "form-style">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать договор</button>
    </form>
</div>

{% endblock %}

core/templates/core/home.html
{% extends 'base.html' %}

{% block content %}
<div class="home-text">
    <h2>Добро пожаловать на сайт EasyRent</h2>
    <p>Здесь вы можете найти и арендовать недвижимость.</p>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'base.html' %}

{% block content %}

<div class="center-container">
    <h2 class = "custom-h2">Вход</h2>
    <form method="post" class = "form-style">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
    </form>
</div>
{% endblock %}

core/templates/core/my_rental_agreements.html
{% extends 'base.html' %}

{% block content %}
  <div class="center-container-property-list">
    <h2 class = "custom-h2">Мои договоры аренды</h2>
  </div>
  <table class="requests-table">
    <thead>
      <tr>
        <th>Объект</th>
        <th>Дата заезда</th>
        <th>Дата выезда</th>
        <th>Цена</th>
        <th>Статус</th>
        <th>Действие</th>
      </tr>
    </thead>
    <tbody>
      {% for agreement in agreements %}
        <tr>
          <td>{{ agreement.viewing_request.property.title }}</td>
          <td>{{ agreement.start_date }}</td>
          <td>{{ agreement.end_date }}</td>
          <td>{{ agreement.rent_price }} руб.</td>
          <td>{{ agreement.get_status_display}} </td>
          <td>
            {% if agreement.status == 'sent' %}
                <form method="post" action="{% url 'core:confirm_rental_agreements' agreement.id %}">
                    {% csrf_token %}
                    <button type="submit" class='body-button'>Подтвердить</button>
                </form>
            {% elif agreement.status == 'pending_confirmed' %}
                На рассмотрении  
            {% elif agreement.status == 'confirmed' %}
              <form method="post" action="{% url 'core:realtor_cancel_sent_agreements' agreement.id %}">
                  {% csrf_token %}
                  <button type="submit" class='body-button'>Отменить подтверждение</button>
              </form>
            {% endif %}
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="6">У вас нет договоров аренды.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="center-container"></div>
{% endblock %}

core/templates/core/my_viewing_requests.html
{% extends 'base.html' %}

{% block content %}
  <div class="center-container-property-list">
    <h2 class = "custom-h2">Мои запросы на просмотр</h2>
  </div>
  
  <table class="requests-table">
    <thead>
      <tr>
        <th>Объект</th>
        <th>Дата запроса</th>
        <th>Статус</th>
      </tr>
    </thead>
    <tbody>
      {% for viewing_request in viewing_requests %}
        <tr>
          <td>{{ viewing_request.property.title }}</td>
          <td>{{ viewing_request.viewing_time }}</td>
          <td>{{ viewing_request.get_status_display }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="3">У вас нет запросов на просмотр.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="center-container"></div>
{% endblock %}

core/templates/core/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="center-container">
        {% if user.role == 'client'%}
            <h2 class="custom-h2">Профиль клиента</h2>
        {% endif %}
        {% if user.role == 'admin'%}
            <h2 class="custom-h2">Профиль администратора</h2>
        {% endif %}
        {% if user.role == 'realtor'%}
            <h2 class="custom-h2">Профиль риелтора</h2>
        {% endif %}
        <div class="profile-icon">
            <img src="{% static user.get_icon %}" alt="User Icon">
        </div>
        <p class="custom-h2">{{ user.username }}!</p>
        <div class="profile-actions">
            {% if user.role == 'client'%}
                <a href="{% url 'core:my_viewing_requests' %}" class="body-button">Мои запросы</a>
                <a href="{% url 'core:my_rental_agreements' %}" class="body-button">Мои договоры</a>
            {% endif %}
            {% if user.role == 'admin'%}
                <a href="/admin/" class="body-button">Админка</a>
            {% endif %}
            {% if user.role == 'realtor'%}
                <a href="{% url 'core:realtor_properties' %}" class="body-button">Мои объявления </a>
                <a href="{% url 'core:realtor_viewing_requests' %}" class="body-button">Запросы на подтверждение</a>
                <a href="{% url 'core:realtor_rental_agreements' %}" class="body-button">Договоры на согласование</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

core/templates/core/property_create.html
{%extends 'base.html' %}

{% block content %}
    <div class="center-container">
        <h2 class="custom-h2">Добавить объект недвижимости</h2>
        
        <form method="post" class="form-style">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Добавить</button>
        </form>
    </div>
{% endblock %}

core/templates/core/property_list.html
{% extends 'base.html' %}

{% block content %}
<div class="center-container-property-list">
    <h2 class = "custom-h2">Список недвижимости</h2>
</div>

<form method="get" class="form-sort-style">
    <label for="sort">Сортировать по:</label>
    <select name="sort" id="sort" onchange="this.form.submit()">
      <option value="price" {% if request.GET.sort == 'price' %}selected{% endif %}>Цене ↓</option>
      <option value="-price" {% if request.GET.sort == '-price' %}selected{% endif %}>Цене ↑</option>
      <option value="area" {% if request.GET.sort == 'area' %}selected{% endif %}>Метражу ↓</option>
      <option value="-area" {% if request.GET.sort == '-area' %}selected{% endif %}>Метражу ↑</option>
    </select>
</form>

<div class="property-list">
    {% for property in properties %}
        <div class="property-card">
            <h3>{{ property.title }}</h3>
            <p>{{ property.description }}</p>
            <p><strong>Цена:</strong> {{ property.price }} руб.</p>
            <p><strong>Площадь:</strong> {{ property.area }} м²</p>
            <p><strong>Местоположение:</strong> {{ property.location }}</p>
            <p><strong>Статус:</strong> {{ property.get_status_display }}</p>

            {% if user.is_authenticated %}
                {% if user.role == 'client'%}
                    <a href="{% url 'core:viewing_request' property.id %}" class="body-button">Запрос на просмотр</a>
                {% endif %}
            {% else %}
                <a href="{% url 'core:login' %}" class="body-button">Запрос на просмотр</a>
            {% endif %}
        </div>
    {% endfor %}
</div>
{% endblock %}

core/templates/core/realtor_properties.html
{% extends 'base.html' %}

{% block content %}
    <div class="center-container-property-list">
        <h2 class="custom-h2">Мои объявления</h2>
        {% if user.is_authenticated %}
            <p><a href="{% url 'core:property_create' %}" class="body-button">Добавить</a></p>
        {% endif %}
    </div>

    <div class="property-list">
        {% for property in properties %}
                <div class="property-card">
                    <h3>{{ property.title }}</h3>
                    <p>{{ property.description }}</p>
                    <p><strong>Цена:</strong> {{ property.price }} руб.</p>
                    <p><strong>Площадь:</strong> {{ property.area }} м²</p>
                    <p><strong>Местоположение:</strong> {{ property.location }}</p>
                    <p><strong>Статус:</strong> {{ property.get_status_display }}</p>
                </div>
        {% empty %}
            <li>Нет объявлений</li>
        {% endfor %}
    </div>

    <div class="center-container-2"> </div>
{% endblock %}

core/templates/core/realtor_rental_agreements.html
{% extends 'base.html' %}

{% block content %}
  <div class="center-container-property-list">
    <h2 class = "custom-h2">Мои договоры аренды</h2>
  </div>
  <table class="requests-table">
    <thead>
      <tr>
        <th>Арендатор</th>
        <th>Риелтор</th>
        <th>Объект</th>
        <th>Дата заезда</th>
        <th>Дата выезда</th>
        <th>Цена</th>
        <th>Статус</th>
        <th>Действие</th>
      </tr>
    </thead>
    <tbody>
      {% for agreement in agreements %}
        <tr>
          <td>{{ agreement.tenant }}</td>
          <td>{{ agreement.realtor }}</td>
          <td>{{ agreement.viewing_request.property.title }}</td>
          <td>{{ agreement.start_date }}</td>
          <td>{{ agreement.end_date }}</td>
          <td>{{ agreement.rent_price }} руб.</td>
          <td>{{ agreement.get_status_display }}</td>
          <td>
            {% if agreement.status == 'pending_sent' %}
                <form method="post" action="{% url 'core:realtor_sent_agreements' agreement.id %}">
                    {% csrf_token %}
                    <button type="submit" class='body-button'>Отправить</button>
                </form>
            {% elif agreement.status == 'sent' %}
                <form method="post" action="{% url 'core:realtor_cancel_sent_agreements' agreement.id %}">
                    {% csrf_token %}
                    <button type="submit" class='body-button'>Отменить отправку</button>
                </form>
            {% elif agreement.status == 'pending_confirmed' %}
                <form method="post" action="{% url 'core:realtor_confirm_rental_agreements' agreement.id %}">
                    {% csrf_token %}
                    <button type="submit" class='body-button'>Подтвердить</button>
                </form>   
            {% elif agreement.status == 'confirmed' %}
              <form method="post" action="{% url 'core:realtor_cancel_sent_agreements' agreement.id %}">
                  {% csrf_token %}
                  <button type="submit" class='body-button'>Отменить подтверждение</button>
              </form>
            {% endif %}
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="8">У вас нет договоров аренды.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="center-container"></div>
{% endblock %}

core/templates/core/realtor_viewing_requests.html
{% extends 'base.html' %}

{% block content %}
  <div class="center-container-property-list">
    <h2 class = "custom-h2">Мои запросы на просмотр</h2>
  </div>
  <table class="requests-table">
    <thead>
      <tr>
        <th>Объект</th>
        <th>Дата запроса</th>
        <th>Статус</th>
        <th>Действие</th>
        <th>Договор</th>
      </tr>
    </thead>
    <tbody>
      {% for viewing_request in viewing_requests %}
        <tr>
          <td>{{ viewing_request.property.title }}</td>
          <td>{{ viewing_request.viewing_time }}</td>
          <td>{{ viewing_request.get_status_display  }}</td>
          <td>
            {% if viewing_request.status == 'pending' %}
                <form method="post" action="{% url 'core:confirm_viewing_requests' viewing_request.id %}">
                    {% csrf_token %}
                    <button type="submit" class='body-button'>Подтвердить запись</button>
                </form>
            {% else %}
                <form method="post" action="{% url 'core:cancel_viewing_requests' viewing_request.id %}">
                    {% csrf_token %}
                    <button type="submit" class='body-button'>Отменить запись</button>
                </form>
            {% endif %}
          </td>
          <td>  
            {% if viewing_request.status != 'pending' %}
              <form method="post" action="{% url 'core:create_rental_agreement' viewing_request.id %}">
                {% csrf_token %}
                <button type="submit" class='body-button'>Создать договор</button>
              </form>
            {% else %}
              Необходимо подтверждение
            {% endif %}
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">У вас нет запросов на просмотр.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="center-container"></div>
{% endblock %}

core/templates/core/register.html
{%extends 'base.html' %}

{%block content%}
<div class="center-container">
    <h2 class="custom-h2">Регистрация</h2>
    <form method="post" class = "form-style">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрироваться</button>
    </form>
</div>
{% endblock %}

core/templates/core/viewing_request.html
{% extends 'base.html' %}

{% block content %}
<div class="center-container">
    <h2 class="custom-h2">Запрос на просмотр</h1>

    <form method="post" class="form-style">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Отправить запрос</button>
    </form>

</div>
{% endblock %}